// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/blazee5/url-shortener-rest-api"
	mock "github.com/stretchr/testify/mock"
)

// URLSaver is an autogenerated mock type for the URLSaver type
type URLSaver struct {
	mock.Mock
}

// SaveUrl provides a mock function with given fields: ctx, shortUrl
func (_m *URLSaver) SaveURL(ctx context.Context, shortUrl *models.ShortUrl) error {
	ret := _m.Called(ctx, shortUrl)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.ShortUrl) error); ok {
		r0 = rf(ctx, shortUrl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewURLSaver creates a new instance of URLSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLSaver {
	mock := &URLSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
